### ISSUE TITLE
Recreate all compendium packs for DH 1.4

### ISSUE THREAD

**Issue by JackPyro** [JackPyro/daggerheart#18]

**Comment by JackPyro** [comment]
Fixed all new cards, new ancestry features and community. Left to add new weapon / armor changes

**Comment by JackPyro** [comment]
Took a week to rewrite my parser for data, so now I can easily parse whole pdf and get all subclasses, domain cards, items and stuff more easily in the future. So we super ready for next version

**Comment by ComfortableGreySloth** [comment]
That's so exciting, I was not looking forward to data entry!
